name: UiPath End-to-End CI/CD Pipeline
on:
push:
branches:
	-main
workflow_dispatch:
jobs:
build-and-deploy:
runs-on: windows-latest
# GitHub Environment
environment:
name: production
env:
 # These use secrets configured in your GitHub Repository settings
      UIPATH_URL: "https://cloud.uipath.com/mnscorp/WPT_Prod/orchestrator_" # ${{ secrets.UIPATH_ORCHESTRATOR_URL }}          # e.g., https://uipath.com
      UIPATH_CLIENT_ID: "24514b61-3ea2-473d-a654-2099b5cc6193" # ${{ secrets.UIPATH_EXTERNAL_APP_ID }}     # External App client ID
      UIPATH_CLIENT_SECRET: "axoJfTEgE(AGhZdLEdqK)w?_6iW?`$g1O5Zo?gMrRxvKp4Y`$H6d0KxHrAl@nPJCFH" # ${{ secrets.UIPATH_EXTERNAL_APP_SECRET }} # External App secret
      UIPATH_FOLDER: "Shared" # The Orchestrator Folder to deploy to
      UIPATH_TENANT_NAME: "WPT_Prod"


steps:
- name: Checkout Code
uses: actions/checkout@v4
- name: Setup .NET SDK
uses: actions/setup-dotnet@v4
with:
dotnet-version: "8.0.x"
- name: Install UiPath CLI
shell: pwsh
run: |
npm install -g @uipath/cli
uip tools install @uipath/rpa-tool
- name: Login to Orchestrator
shell: pwsh
run: |
uip login `
--client-id "${{ env.UIPATH_CLIENT_ID }}" `
--client-secret "${{ env.UIPATH_CLIENT_SECRET }}" `
--tenant "${{ env.UIPATH_TENANT_NAME }}" `
--authority "${{ env.UIPATH_URL }}"
o	name: Pack UiPath Project
shell: pwsh
run: |
mkdir output
uip rpa pack "." "./output" --package-version "1.0.${{ github.run_number }}"
- name: Deploy to Orchestrator
shell: pwsh
run: |
$pkg = Get-ChildItem "./output" -Filter .nupkg | Select-Object -First 1
uip or packages upload $pkg.FullName `
--tenant "${{ env.UIPATH_TENANT_NAME }}"
